### ISSUE TITLE
Missing transform_ image function

### ISSUE THREAD

**Issue by SJLeo** [sutd-visual-computing-group/dag-gans#1]
There's no transform_image function in utils.py when I'm training cyclegan

**Comment by tntrung** [comment]
Hi, thanks for the feedback. I've updated the util.py for cyclegan. If it's ok to you, please close the issue. Thanks.

**Comment by SJLeo** [comment]
Thank you, but I'm a little puzzled if only rotation or flipping is used on cyclegan, and other data augument is not effective.

**Comment by tntrung** [comment]
Hi, we've only tested with rotation and flipping for cyclegan so far, but I believe that other data augmentations like translation, cropping, ... or their combinations are effective too as we did with other GANs in our paper.

**Comment by SJLeo** [comment]
It seems that we can't use multiple data augument methods at the same time.

**Comment by tntrung** [comment]
For current implementation for cyclegan, we test only with a single augmentation for the demonstration with image-image translation, will update multiple methods in the near future. If you prefer to use multiple augmentations, may refer our published pytorch module.

**Comment by SJLeo** [comment]
Thanks!
